development:
  pusher_app_id: <%= ENV["pusher_app_id"] %>
  pusher_key: <%= ENV["pusher_key"] %>
  pusher_secret: <%= ENV["pusher_secret"] %>

test:
  pusher_api: 

production:
  pusher_app_id: <%= ENV["pusher_app_id"] %>
  pusher_key: <%= ENV["pusher_key"] %>
  pusher_secret: <%= ENV["pusher_secret"] %>
